### ISSUE TITLE
xbmcup & kodi 17

### ISSUE THREAD

**Issue by Durlyn** [xbmc-addon/repository.hal9000#1]
Hi!

in kodi 17 xbmcup not work. This error says:

09:15:29 T:139838764336896 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.ImportError'>
  Error Contents: cannot import name ControlCheckMark
  Traceback (most recent call last):
  File "/home/xbmc/.kodi/addons/script.module.xbmcup/service.py", line 14, in <module>
  run()
  File "/home/xbmc/.kodi/addons/script.module.xbmcup/service.py", line 10, in run
  from xbmcup.cache import CacheServer
  File "/home/xbmc/.kodi/addons/script.module.xbmcup/lib/xbmcup/cache.py", line 16, in <module>
  import gui
  File "/home/xbmc/.kodi/addons/script.module.xbmcup/lib/xbmcup/gui.py", line 13, in <module>
  import _control as control
  File "/home/xbmc/.kodi/addons/script.module.xbmcup/lib/xbmcup/_control.py", line 6, in <module>
  from xbmcgui import ControlButton, ControlCheckMark, ControlEdit, ControlFadeLabel, ControlGroup, ControlImage,\
  ImportError: cannot import name ControlCheckMark
  -->End of Python script error report<--
  09:19:34 T:139839317710592 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

**Comment by xbmc-addon** [comment]
Fixed
